### ISSUE TITLE
error: argument --arch/-a: invalid choice: 'robertaEMO'

### ISSUE THREAD

**Issue by cuczy** [shamanez/BERT-like-is-All-You-Need#2]
Hello, thank you very much for being able to open source your code,I am very interested in your work, but in the process of reproducing, there was an error of "robertaEMO" parameter invalid selection, I hope you can help me where the problem is

**Comment by shamanez** [comment]
Can you screeen shot the error. Make sure you install the fairseq first
with pip.

**Comment by shamanez** [comment]
For now try

robertaEMO_large

**Comment by cuczy** [comment]
I have successfully installed fairseq in pycharm. I changed roberta to roberta_large as you said and still got the same error. There is no robertaEMO available in the parameter options provided after the error message. I will send the screenshot to your Mailbox.

**Comment by shamanez** [comment]
Is it windows?

**Comment by shamanez** [comment]
Change to robertaEMO_large

**Comment by cuczy** [comment]
I changed it to robertaEMO_large and still the same error

**Comment by shamanez** [comment]
Oh sorry mistake..

**robertEMO_large**

**Comment by cuczy** [comment]
Thank you very much, that error disappeared, but a new error appeared
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by shamanez** [comment]
Can you send me the full error. Also are u using windows?

**Comment by cuczy** [comment]
I am using macos and the screenshot has been sent to your email

**Comment by shamanez** [comment]
Sent to shamane@ahlab.org

**Comment by cuczy** [comment]
I have sent the screenshot to the email address you provided

**Comment by shamanez** [comment]
Put your model address here,
https://github.com/shamanez/BERT-like-is-All-You-Need/blob/master/fairseq/models/mult_emo.py#L58


also, use the wav2vec K-Means checkpoint.

**Comment by Nie-Yingying** [comment]
Hi,

When loading 'roberta.large', there is still the same error.  Below is the log:

============================================================================
2020-12-16 10:52:24 | INFO | fairseq.file_utils | http://dl.fbaipublicfiles.com/fairseq/models/roberta.large.tar.gz not found in cache, downloading to /tmp/tmp30jysthl
 18%|████████████▊                                                           | 117103616/655283069 [08:46<32:04:56, 4659.71B/s]2020-12-16 11:01:22 | INFO | fairseq.file_utils | Archive name 'http://dl.fbaipublicfiles.com/fairseq/models/roberta.large.tar.gz' was not found in archive name list. We assumed 'http://dl.fbaipublicfiles.com/fairseq/models/roberta.large.tar.gz' was a path or URL but couldn't find any file associated to this path or URL.
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    cli_main()
  File "/raid/user11/workspace/developer/speechEmotionRecogniton/BERT-like-is-All-You-Need-master/fairseq_cli/train.py", line 355, in cli_main
    main(args)
  File "/raid/user11/workspace/developer/speechEmotionRecogniton/BERT-like-is-All-You-Need-master/fairseq_cli/train.py", line 73, in main
    model = task.build_model(args)
  File "/raid/user11/workspace/developer/speechEmotionRecogniton/BERT-like-is-All-You-Need-master/fairseq/tasks/emotion_prediction.py", line 110, in build_model
    model = models.build_model(args, self) #/home/gsir059/Documents/PhD/MulFie/fairseq/fairseq/models/__init__.py'
  File "/raid/user11/workspace/developer/speechEmotionRecogniton/BERT-like-is-All-You-Need-master/fairseq/models/__init__.py", line 48, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/raid/user11/workspace/developer/speechEmotionRecogniton/BERT-like-is-All-You-Need-master/fairseq/models/mult_emo.py", line 162, in build_model
    return cls(args, encoder)
  File "/raid/user11/workspace/developer/speechEmotionRecogniton/BERT-like-is-All-You-Need-master/fairseq/models/mult_emo.py", line 67, in __init__
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
  File "/home/user4/anaconda3/envs/pytorch16/lib/python3.6/site-packages/torch/hub.py", line 353, in load
    model = entry(*args, **kwargs)
  File "/raid/user11/workspace/developer/speechEmotionRecogniton/BERT-like-is-All-You-Need-master/fairseq/models/roberta/model.py", line 149, in from_pretrained
    **kwargs,
  File "/raid/user11/workspace/developer/speechEmotionRecogniton/BERT-like-is-All-You-Need-master/fairseq/hub_utils.py", line 56, in from_pretrained
    kwargs['data'] = os.path.abspath(os.path.join(model_path, data_name_or_path))
  File "/home/user4/anaconda3/envs/pytorch16/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
 18%|█████████████                                                            | 117104640/655283069 [08:56<41:07, 218076.78B/s]
==============================================================================


I want to konw if I have prepared the 'reoberta.large' model, which path I should put it in.  And any suggestion is grateful.

**Comment by Nie-Yingying** [comment]
The problem is solved and thanks all the same.

**Comment by shamanez** [comment]
In the script you need to change the path
